
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">	
        <li>
         <?php $_banks = $this->getIdealIssuers(); ?>
		 <select name="payment[bankid]" class="input-text" id="<?php echo $this->escapeHtml($this->getMethodCode()) ?>_bank_id" title="<?php echo $this->escapeHtml($this->getMethodCode()) ?>_bank_id">
				<?php foreach ($_banks as $bank){ ?>
					<option value="<?php echo $bank['code']['VALUE'] ?>"><?php echo $bank['description']['VALUE'] ?></option>
				<?php } ?>
			</select>
		 
        </li>

    </ul>
</fieldset>