<?php
$_code=$this->getMethodCode();
?>



    <ul  class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none">	
        <li>
         <?php $_banks = $this->getIdealIssuers(); ?>
		 <select id="<?php echo $_code ?>_bank" name="payment[<?php echo $_code ?>_bank]" class="input-text validate-text required-entry">
			<option value=""><?php echo $this->__('Selecteer een bank...'); ?></option>
				<?php foreach ($_banks as $bank){ ?>
					<option value="<?php echo $bank['code']['VALUE'] ?>"><?php echo $bank['description']['VALUE'] ?></option>
				<?php } ?>
			</select>
		 
        </li>

    </ul>
